Libreria/Controllers/AgregarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Libreria.Controllers
{
    public class AgregarController : Controller
    {
        // GET: Agregar
        public ActionResult Registrar()
        {
            return View();
        }


        public void InsertEditorial(string editorial)
        {
            
        }
    }
}

Libreria/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Libreria.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Libreria/Views/Agregar/Registrar.cshtml
@*<script src="~/assets/js/AngularController/Part2Controller.js"></script>*@

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script>
    function justNumbers(e) {
        var keynum = window.event ? window.event.keyCode : e.which;
        if ((keynum == 8) || (keynum == 46))
            return true;

        return /\d/.test(String.fromCharCode(keynum));
    }

    //function arti() {

    //    $scope.Products.forEach(function (a) {
    //        if (a.CodProducto == $scope.producto) {
    //            $scope.producto1 = a.DescripcionProducto;
    //        }
    //        console.log($scope.producto1);
    //    })
    //}
</script>
@* I will add some css for looks good *@
<style>
    input[type=checkbox] {
        width: 18px;
        height: 18px;
    }

    input[type=radio] {
        width: 15px;
        height: 15px;
    }

    .tableData {
        border-left: solid 1px #D8C3C3;
        border-top: solid 1px #D8C3C3;
    }


    .md-progress-circular {
        left: 199px;
    }

    .tableData tr {
    }


    .tableData td, .tableData th {
        border-right: solid 1px #D8C3C3;
        border-bottom: solid 1px #D8C3C3;
        text-align: left;
        padding: 5px;
    }

    .tableData td {
    }

    .tableData th {
        /*background-color: #FAFAFA;
            padding: 7px 5px;
            border-bottom-color: #9C9C9C;*/
    }

    .odd {
        background-color: #f3f3f3;
    }

    .highlight {
        color: #ff0000;
    }

    .even {
        background-color: #ffffff;
    }

    input[type=text] {
        width: 300px;
        box-sizing: border-box;
    }

    .margin_app {
        margin-left: 20px;
    }

    .box-title {
        font-size: 30px;
    }
    /*

        style="float:left; width: 50%; height:100%; border-right: 1px solid gray;
        */
</style>


<div ng-controller="Ctrl" ng-cloak class="margin_app">

    <div class="box-header with-border ">
        <h2 class="">Buscar / Agregar</h2>
    </div>

    <div class="BuscaProductos col-md-5">
       
        <div id="buscaProductosCampos" class="form-inline" style="margin-top:30px">

            <div class="form-group" style="margin-right:20px">
               
                <b>Titulo:</b>
                <select class="form-control" ng-model="titulo">
                    <option value="value">text</option>
                </select>
               
            </div>
            <div id="ProveedorTextbox" class="form-group">
                
                <b>Categoria:</b>
                <select class="form-control" ng-model="categoria">
                    <option value="value">text</option>
                </select>

            </div>

            <div style="margin-top:25px;" class="form-group">

                <div class="input-group-btn">
                    <button ng-click="search()" type="button" class="btn btn-default"><i class="fa fa-search" aria-hidden="true"></i>&nbsp; Buscar...</button>
                    <button ng-click="clean('txtAutocomplete')" type="button" class="btn btn-danger"><i class="fa fa-eraser" aria-hidden="true"></i>&nbsp; Limpiar...</button>
                </div>
            </div>
        </div>

        <md-progress-circular ng-show="isLoadingB" md-mode="indeterminate" md-diameter="70" style="left:223px;"></md-progress-circular>

        <div id="tablabuscaProducto" ng-show="!isLoadingB" style="margin-top: 25px">
            <div class="table-responsive" style="height:400px; overflow-y:scroll;" ng-show="Contact.length > 0">
                <table class="table table-bordered table-responsive">
                    <thead class="theadProducto">
                        <tr>
                            <th>Titulo</th>
                            <th>Editorial</th>
                            <th>Categoria</th>
                            <th>Autor</th>
                            <th>Formato</th>
                            <th>Idioma</th> 
                        </tr>
                    </thead>
                    <tbody class="tbodyProducto">
                        <tr ng-click="detail(Contact[$index])" ng-repeat="x in Contact">
                            <td>{{x.CodProducto}}</td>
                            <td>{{x.DescripcionProducto}}</td>
                            <td>{{x.IdUnidadAlmacenaje}}</td>
                            <td>{{x.Disponible}}</td>
                        </tr>
                    </tbody>
                </table>

            </div>

        </div>
    </div>


    <div class="container">
        <div class="col-md-7">
            <ul class="nav nav-tabs">
                <li class="active"><a class="ColorTab" data-toggle="tab" href="#datos">Registrar Libro</a></li>
                <li><a data-toggle="tab" class="ColorTab" href="#CamposModificables">Editorial</a></li>
                <li><a class="ColorTab" data-toggle="tab" href="#ubicacion">Ejemplar</a></li>
                <li><a class="ColorTab" data-toggle="tab" href="#ubicacion1">Idiomas</a></li>
                <li><a class="ColorTab" data-toggle="tab" href="#ubicacion2">Direccion</a></li>
                <li><a class="ColorTab" data-toggle="tab" href="#ubicacion3">Formato</a></li>
                <li><a class="ColorTab" data-toggle="tab" href="#ubicacion4">Autor</a></li>
            </ul>
            <div class="tab-content" style="margin-top:30px">
                <div id="datos" class="tab-pane fade in active">

                    <form>

                        <div class="form-group">
                            <label for="seccion">Titulo del Libro</label>
                            <input type="text" ng-model="tituloLibro" class="form-control" placeholder="Sección">
                        </div>
                        <div class="form-group">
                            <label for="seccion">Autor:</label>
                            <select class="form-control" ng-model="autorLibro" ng-init="autorLibro = ''">
                                <option value="value">Seleccione</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="seccion">Formato:</label>
                            <select class="form-control" ng-model="formatoLibro" ng-init="formatoLibro = ''">
                                <option value="value">Seleccione</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="seccion">Idioma:</label>
                            <select class="form-control" ng-model="idiomaLibro" ng-init="idiomaLibro = ''">
                                <option value="value">Seleccione</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="seccion"ng-model="editorialLibro" ng-init="editorialLibro = ''">Editorial:</label>
                            <select class="form-control">
                                <option value="value">Seleccione</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="seccion" ng-model="categoriaLibro" ng-init="categoriaLibro = ''">Categoria:</label>
                            <select class="form-control">
                                <option value="value">Seleccione</option>
                            </select>
                        </div>
                    </form>


                </div>
                <div id="ubicacion" class="tab-pane fade">

                    <div class="form-group">
                        <label for="DiasMinimoCaducidad">Nombre Ejemplar:</label>
                        <input type="text" ng-model="Ejemplar" class="form-control" placeholder="Días Mínimo Caducidad">
                    </div>

                    <button ng-show="!isLoading" id="botonActualizar" type="button" ng-click="Actualizar()" class="btn btn-danger"><i class="fa fa-save" aria-hidden="true"></i>&nbsp; Modificar</button>

                </div>
                <div id="ubicacion1" class="tab-pane fade">

                    <div class="form-group">
                        <label for="DiasMinimoCaducidad">Idioma:</label>
                        <input type="text" ng-model="Idioma" class="form-control" placeholder="Días Mínimo Caducidad">
                    </div>

                    <button ng-show="!isLoading" id="botonActualizar" type="button" ng-click="Actualizar()" class="btn btn-danger"><i class="fa fa-save" aria-hidden="true"></i>&nbsp; Modificar</button>

                </div>
                <div id="ubicacion2" class="tab-pane fade">

                    <div class="form-group">
                        <label for="DiasMinimoCaducidad">Direccion:</label>
                        <input type="text" ng-model="Direccion" class="form-control" placeholder="Días Mínimo Caducidad">
                    </div>

                    <button ng-show="!isLoading" id="botonActualizar" type="button" ng-click="Actualizar()" class="btn btn-danger"><i class="fa fa-save" aria-hidden="true"></i>&nbsp; Modificar</button>

                </div>
                <div id="ubicacion3" class="tab-pane fade">

                    <div class="form-group">
                        <label for="DiasMinimoCaducidad">Formato:</label>
                        <input type="text" ng-model="Formato" class="form-control" placeholder="Días Mínimo Caducidad">
                    </div>

                    <button ng-show="!isLoading" id="botonActualizar" type="button" ng-click="Actualizar()" class="btn btn-danger"><i class="fa fa-save" aria-hidden="true"></i>&nbsp; Modificar</button>

                </div>
                <div id="ubicacion4" class="tab-pane fade">

                    <div class="form-group">
                        <label for="DiasMinimoCaducidad">Autor:</label>
                        <input type="text" ng-model="Autor" class="form-control" placeholder="Días Mínimo Caducidad">
                    </div>

                    <button ng-show="!isLoading" id="botonActualizar" type="button" ng-click="Actualizar()" class="btn btn-danger"><i class="fa fa-save" aria-hidden="true"></i>&nbsp; Modificar</button>

                </div>
                <div id="CamposModificables" class="tab-pane fade">

                    <md-progress-circular ng-show="isLoading" md-mode="indeterminate" md-diameter="70" style="left:223px;"></md-progress-circular>
                    <div class="col-md-6" ng-show="!isLoading">


                        <div class="form-group">
                            <label for="DiasMinimoCaducidad">Nombre Editorial:</label>
                            <input type="text" ng-model="Editorial" class="form-control" placeholder="Días Mínimo Caducidad">
                        </div>

                        <button ng-show="!isLoading" id="botonActualizar" type="button" ng-click="InsertEditorial()" class="btn btn-danger"><i class="fa fa-save" aria-hidden="true"></i>&nbsp; Modificar</button>

                    </div>
                    <div class="col-md-6" ng-show="!isLoading">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@*@section scripts{
        <script src="~/Scripts/AngularController/Part2Controller.js"></script>

    }*@

Libreria/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Libreria/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Libreria/Views/Home/Index.cshtml
<div ng-controller="Ctrl" >
    <div class="row" style="padding-right:42px; margin-top: 20px;">
        <div class="col-lg-12" style="padding-right:0px">
            <img src="~/Img/fotoo.jpg" alt="Alternate Text" height="500px" width="340px" />
        </div>
    </div>

    <div class="row" style="padding-right:42px">
        <div class="col-lg-12" style="padding-right:0px">
            <div class="jumbotron">
                <h1>Bienvenido/a:</h1>
                <p>Aplicación web destinada a la gestíon de los libros de una libreria.</p>
            </div>
        </div>
    </div>
</div>














@*@{
    ViewBag.Title = "Home Page";
}



<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

Libreria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
    <meta charset="utf-8" />
    @*<script src="~/Scripts/angular.js"></script>*@
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=no" name="viewport" />
    <meta content="Semantic-UI-Forest, collection of design, themes and templates for Semantic-UI." name="description" />
    <meta content="Semantic-UI, Theme, Design, Template" name="keywords" />
    <meta content="PPType" name="author" />
    <meta content="#ffffff" name="theme-color" />
    <title>Semantic-UI-Forest, collection of design, themes and templates for Semantic-UI.</title>
    @*<link href="../../static/dist/semantic-ui/semantic.min.css" rel="stylesheet" type="text/css" />
        <link href="../../static/stylesheets/default.css" rel="stylesheet" type="text/css" />
        <link href="../../static/stylesheets/pandoc-code-highlight.css" rel="stylesheet" type="text/css" />
        <script src="../../static/dist/jquery/jquery.min.js"></script>*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body  ng-app="myapp" style="padding: 0px;">
    <div class="ui inverted huge borderless fixed fluid menu">
        <a class="header item" href="@Url.Action( "Index", "Home")">Gestor de Libreria</a>
        <div class="right menu">
            @*<div class="item">
                <div class="ui small input">
                    <input placeholder="Search..." />
                </div>
            </div>*@
            <a class="item" href="@Url.Action( "Index", "Home")">Inicio</a>
            @*<a class="item">Settings</a>
            <a class="item">Profile</a>
            <a class="item">Help</a>*@
        </div>
    </div>
    <div class="ui grid" style="padding:0px">
        <div class="row">
            <div class="column" id="sidebar">
                <div class="ui secondary vertical fluid menu">
                    <a class="active item" href="@Url.Action( "Index", "Home")">Inicio</a>
                    <a class="item" href="@Url.Action( "Registrar", "Agregar")">Registrar Libro</a>
                    <a class="item">Ver Libros</a>
                    <a class="item">Ver Libros</a>
                    @*<div class="ui hidden divider"></div>
                    <a class="item">Nav item</a>
                    <a class="item">Nav item again</a>
        <a class="item">One more nav</a>
        <a class="item">Another nav item</a>
        <a class="item">More navigation</a>
        <div class="ui hidden divider"></div>
        <a class="item">Macintosh</a>
        <a class="item">Linux</a>
        <a class="item">Windows</a>*@
                </div>
            </div>
            <div class="column" id="content" >
                @RenderBody()
                @*<div class="ui grid">
                    <div class="row">
                        <h1 class="ui huge header">
                            Dashboard
                        </h1>
                    </div>
                    <div class="ui divider"></div>
                    <div class="ui hidden section divider"></div>
                    <div class="row">
                        <h1 class="ui huge header">
                            Section title
                        </h1>
                    </div>
                    <div class="ui divider"></div>
                </div>*@
            </div>
        </div>
    </div>
    <style type="text/css">

        body {
            display: relative;
        }

        #sidebar {
            position: fixed;
            top: 45.8px;
            left: 0;
            bottom: 0;
            width: 18%;
            background-color: #f5f5f5;
            padding: 0px;
        }

            #sidebar .ui.menu {
                margin: 2em 0 0;
                font-size: 16px;
            }

                #sidebar .ui.menu > a.item {
                    color: #337ab7;
                    border-radius: 0 !important;
                }

                    #sidebar .ui.menu > a.item.active {
                        background-color: #337ab7;
                        color: white;
                        border: none !important;
                    }

                    #sidebar .ui.menu > a.item:hover {
                        background-color: #4f93ce;
                        color: white;
                    }

        #content {
            margin-left: 19%;
            width: 81%;
            margin-top: 3em;
            padding-left: 3em;
            float: left;
        }

            #content > .ui.grid {
                padding-right: 4em;
                padding-bottom: 3em;
            }

            #content h1 {
                font-size: 36px;
            }

            #content .ui.divider:not(.hidden) {
                margin: 0;
            }

            #content table.ui.table {
                border: none;
            }

                #content table.ui.table thead th {
                    border-bottom: 2px solid #eee !important;
                }
    </style>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/Scripts/js")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@